[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback so any route serves index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200